"""
SDR Generator - Produces a Solution Design Reference (tracking plan)
spreadsheet from page analyses. The SDR is the central artifact that
maps every recommended event to its trigger, parameters, and business purpose.
"""

import json
import logging
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

logger = logging.getLogger(__name__)

# Color scheme
HEADER_FILL = PatternFill("solid", fgColor="1B3A5C")  # Dark navy
HEADER_FONT = Font(name="Arial", bold=True, color="FFFFFF", size=11)
SUBHEADER_FILL = PatternFill("solid", fgColor="4A90C4")
SUBHEADER_FONT = Font(name="Arial", bold=True, color="FFFFFF", size=10)
STANDARD_FONT = Font(name="Arial", size=10)
STANDARD_EVENT_FILL = PatternFill("solid", fgColor="E8F5E9")  # Light green for GA4 standard
CUSTOM_EVENT_FILL = PatternFill("solid", fgColor="FFF3E0")  # Light orange for custom
HIGH_PRIORITY_FONT = Font(name="Arial", size=10, bold=True, color="C62828")
MEDIUM_PRIORITY_FONT = Font(name="Arial", size=10, color="EF6C00")
LOW_PRIORITY_FONT = Font(name="Arial", size=10, color="757575")
LINK_FONT = Font(name="Arial", size=10, color="1565C0", underline="single")
TITLE_FONT = Font(name="Arial", bold=True, size=14, color="1B3A5C")
SUBTITLE_FONT = Font(name="Arial", size=11, color="616161")
THIN_BORDER = Border(
    left=Side(style="thin", color="D0D0D0"),
    right=Side(style="thin", color="D0D0D0"),
    top=Side(style="thin", color="D0D0D0"),
    bottom=Side(style="thin", color="D0D0D0"),
)


def generate_sdr(analyses, output_path: str, site_name: str = "Oaklandish.com"):
    """Generate the SDR spreadsheet from page analyses."""
    wb = Workbook()

    # --- Sheet 1: Overview ---
    ws_overview = wb.active
    ws_overview.title = "Overview"
    _build_overview_sheet(ws_overview, analyses, site_name)

    # --- Sheet 2: Event Tracking Plan ---
    ws_events = wb.create_sheet("Event Tracking Plan")
    _build_events_sheet(ws_events, analyses)

    # --- Sheet 3: Parameters Reference ---
    ws_params = wb.create_sheet("Parameters Reference")
    _build_params_sheet(ws_params, analyses)

    # --- Sheet 4: Page Inventory ---
    ws_pages = wb.create_sheet("Page Inventory")
    _build_pages_sheet(ws_pages, analyses)

    # --- Sheet 5: Data Layer Spec ---
    ws_datalayer = wb.create_sheet("Data Layer Spec")
    _build_datalayer_sheet(ws_datalayer, analyses)

    wb.save(output_path)
    logger.info(f"SDR saved to {output_path}")


def _apply_header_row(ws, row, headers, col_widths=None):
    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=row, column=col_idx, value=header)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = THIN_BORDER
    if col_widths:
        for col_idx, width in enumerate(col_widths, 1):
            ws.column_dimensions[get_column_letter(col_idx)].width = width


def _apply_cell_style(cell, font=None, fill=None, wrap=True):
    cell.font = font or STANDARD_FONT
    if fill:
        cell.fill = fill
    cell.alignment = Alignment(vertical="top", wrap_text=wrap)
    cell.border = THIN_BORDER


def _build_overview_sheet(ws, analyses, site_name):
    ws.sheet_properties.tabColor = "1B3A5C"

    ws.merge_cells("A1:F1")
    title_cell = ws["A1"]
    title_cell.value = f"GA4 Tracking Plan — {site_name}"
    title_cell.font = TITLE_FONT
    title_cell.alignment = Alignment(vertical="center")
    ws.row_dimensions[1].height = 35

    ws.merge_cells("A2:F2")
    ws["A2"].value = "Solution Design Reference (SDR) — Generated by GA4 AutoTrack"
    ws["A2"].font = SUBTITLE_FONT

    ws.merge_cells("A3:F3")
    ws["A3"].value = "This document defines all GA4 events, parameters, and triggers for the site."
    ws["A3"].font = Font(name="Arial", size=10, color="9E9E9E")

    # Summary stats
    row = 5
    ws.cell(row=row, column=1, value="Summary").font = Font(name="Arial", bold=True, size=12, color="1B3A5C")
    row += 1

    total_events = sum(len(a.recommended_events) for a in analyses)
    standard_events = sum(1 for a in analyses for e in a.recommended_events if e.get("is_standard"))
    custom_events = total_events - standard_events
    page_types = len(set(a.page_type for a in analyses))

    stats = [
        ("Pages Analyzed", len(analyses)),
        ("Distinct Page Types", page_types),
        ("Total Events Recommended", total_events),
        ("GA4 Standard Events", standard_events),
        ("Custom Events", custom_events),
    ]

    for label, value in stats:
        ws.cell(row=row, column=1, value=label).font = Font(name="Arial", size=10, bold=True)
        ws.cell(row=row, column=2, value=value).font = STANDARD_FONT
        row += 1

    row += 1
    ws.cell(row=row, column=1, value="Page Types Covered").font = Font(name="Arial", bold=True, size=12, color="1B3A5C")
    row += 1
    _apply_header_row(ws, row, ["Page Type", "URL Example", "Purpose", "Events Count"], [20, 45, 50, 15])
    row += 1

    for a in analyses:
        event_count = len(a.recommended_events)
        ws.cell(row=row, column=1, value=a.page_type.replace("_", " ").title())
        _apply_cell_style(ws.cell(row=row, column=1))
        ws.cell(row=row, column=2, value=a.url)
        _apply_cell_style(ws.cell(row=row, column=2), font=LINK_FONT)
        ws.cell(row=row, column=3, value=a.page_purpose)
        _apply_cell_style(ws.cell(row=row, column=3))
        ws.cell(row=row, column=4, value=event_count)
        _apply_cell_style(ws.cell(row=row, column=4))
        row += 1

    ws.column_dimensions["A"].width = 22
    ws.column_dimensions["B"].width = 45
    ws.column_dimensions["C"].width = 55
    ws.column_dimensions["D"].width = 15


def _build_events_sheet(ws, analyses):
    ws.sheet_properties.tabColor = "4CAF50"

    headers = [
        "Event Name",
        "Standard/Custom",
        "Priority",
        "Page Type(s)",
        "Trigger Description",
        "Parameters",
        "Business Purpose",
        "Implementation Notes",
    ]
    col_widths = [22, 16, 10, 18, 40, 45, 40, 35]
    _apply_header_row(ws, 1, headers, col_widths)
    ws.auto_filter.ref = f"A1:H1"
    ws.freeze_panes = "A2"

    # Deduplicate events across pages (same event_name gets merged page types)
    event_map = {}
    for a in analyses:
        for e in a.recommended_events:
            name = e["event_name"]
            if name in event_map:
                event_map[name]["page_types"].add(a.page_type)
                # Take higher priority
                prio_order = {"high": 0, "medium": 1, "low": 2}
                if prio_order.get(e.get("priority", "low"), 2) < prio_order.get(event_map[name]["priority"], 2):
                    event_map[name]["priority"] = e["priority"]
            else:
                # Find business purpose from trackable actions
                biz_purpose = ""
                for action in a.trackable_actions:
                    if any(keyword in action["action"].lower() for keyword in name.replace("_", " ").split()):
                        biz_purpose = action["business_value"]
                        break

                event_map[name] = {
                    "event_name": name,
                    "is_standard": e.get("is_standard", False),
                    "priority": e.get("priority", "medium"),
                    "page_types": {a.page_type},
                    "trigger_description": e.get("trigger_description", ""),
                    "parameters": e.get("parameters", {}),
                    "business_purpose": biz_purpose,
                }

    # Sort: high priority first, then standard before custom
    sorted_events = sorted(
        event_map.values(),
        key=lambda x: (
            {"high": 0, "medium": 1, "low": 2}.get(x["priority"], 2),
            0 if x["is_standard"] else 1,
            x["event_name"],
        ),
    )

    row = 2
    for event in sorted_events:
        fill = STANDARD_EVENT_FILL if event["is_standard"] else CUSTOM_EVENT_FILL
        prio = event["priority"]
        prio_font = {"high": HIGH_PRIORITY_FONT, "medium": MEDIUM_PRIORITY_FONT, "low": LOW_PRIORITY_FONT}.get(prio, STANDARD_FONT)

        params_str = "\n".join(f"• {k}: {v}" for k, v in event["parameters"].items())
        page_types_str = ", ".join(sorted(pt.replace("_", " ").title() for pt in event["page_types"]))

        impl_notes = ""
        if event["is_standard"]:
            impl_notes = f"Use GA4 recommended event '{event['event_name']}'. Follow standard parameter schema."
        else:
            impl_notes = "Custom event — requires custom dimension setup in GA4 Admin."

        values = [
            event["event_name"],
            "GA4 Standard" if event["is_standard"] else "Custom",
            prio.upper(),
            page_types_str,
            event["trigger_description"],
            params_str,
            event["business_purpose"],
            impl_notes,
        ]

        for col_idx, val in enumerate(values, 1):
            cell = ws.cell(row=row, column=col_idx, value=val)
            _apply_cell_style(cell, fill=fill)
            if col_idx == 3:
                cell.font = prio_font
            if col_idx == 1:
                cell.font = Font(name="Arial", size=10, bold=True)

        ws.row_dimensions[row].height = max(45, 18 * max(1, params_str.count("\n") + 1))
        row += 1


def _build_params_sheet(ws, analyses):
    ws.sheet_properties.tabColor = "FF9800"

    headers = ["Parameter Name", "Type", "Scope", "Used In Events", "Description / Source", "Example Value"]
    col_widths = [22, 12, 14, 35, 40, 25]
    _apply_header_row(ws, 1, headers, col_widths)
    ws.auto_filter.ref = "A1:F1"
    ws.freeze_panes = "A2"

    # Collect all unique parameters across all events
    param_map = {}
    for a in analyses:
        for e in a.recommended_events:
            for param_name, param_desc in e.get("parameters", {}).items():
                if param_name not in param_map:
                    param_map[param_name] = {
                        "name": param_name,
                        "events": set(),
                        "description": param_desc,
                        "example": "",
                    }
                param_map[param_name]["events"].add(e["event_name"])

        # Enrich with data points
        for dp in a.data_points:
            name = dp["name"]
            if name in param_map:
                param_map[name]["example"] = dp.get("example_value", "")
                if not param_map[name]["description"]:
                    param_map[name]["description"] = dp.get("source", "")
            else:
                param_map[name] = {
                    "name": name,
                    "events": set(),
                    "description": dp.get("source", ""),
                    "example": dp.get("example_value", ""),
                }

    # Determine parameter scope and type
    def classify_param(name):
        item_params = {"item_id", "item_name", "item_brand", "item_category", "item_category2",
                       "item_variant", "price", "quantity", "index", "coupon", "discount"}
        event_params = {"currency", "value", "items", "search_term", "method",
                        "content_type", "promotion_id", "promotion_name", "creative_name",
                        "creative_slot", "item_list_id", "item_list_name"}

        if name in item_params:
            return "Item-scope", "string/number"
        elif name in event_params:
            return "Event-scope", "varies"
        elif name.startswith("page_"):
            return "Event-scope", "string"
        else:
            return "Event-scope (custom)", "string"

    row = 2
    for param in sorted(param_map.values(), key=lambda x: x["name"]):
        scope, ptype = classify_param(param["name"])
        events_str = ", ".join(sorted(param["events"]))

        values = [
            param["name"],
            ptype,
            scope,
            events_str,
            param["description"],
            param["example"],
        ]
        for col_idx, val in enumerate(values, 1):
            cell = ws.cell(row=row, column=col_idx, value=val)
            _apply_cell_style(cell)
        row += 1


def _build_pages_sheet(ws, analyses):
    ws.sheet_properties.tabColor = "2196F3"

    headers = ["URL", "Page Type", "Purpose", "Interactive Elements", "Key Actions to Track"]
    col_widths = [45, 16, 45, 45, 45]
    _apply_header_row(ws, 1, headers, col_widths)
    ws.freeze_panes = "A2"

    row = 2
    for a in analyses:
        elements_str = "\n".join(f"• {el['element']}" for el in a.interactive_elements[:8])
        actions_str = "\n".join(f"• {act['action']}" for act in a.trackable_actions[:6])

        values = [
            a.url,
            a.page_type.replace("_", " ").title(),
            a.page_purpose,
            elements_str,
            actions_str,
        ]
        for col_idx, val in enumerate(values, 1):
            cell = ws.cell(row=row, column=col_idx, value=val)
            _apply_cell_style(cell)
            if col_idx == 1:
                cell.font = LINK_FONT

        ws.row_dimensions[row].height = max(60, 16 * max(elements_str.count("\n"), actions_str.count("\n"), 1))
        row += 1


def _build_datalayer_sheet(ws, analyses):
    ws.sheet_properties.tabColor = "9C27B0"

    ws.merge_cells("A1:D1")
    ws["A1"].value = "dataLayer Push Specifications"
    ws["A1"].font = Font(name="Arial", bold=True, size=13, color="1B3A5C")
    ws.row_dimensions[1].height = 30

    ws.merge_cells("A2:D2")
    ws["A2"].value = "These are the dataLayer.push() calls that should be implemented on the site. GTM triggers will listen for these events."
    ws["A2"].font = Font(name="Arial", size=10, color="757575")

    row = 4

    # Collect unique events
    seen = set()
    for a in analyses:
        for e in a.recommended_events:
            if e["event_name"] in seen:
                continue
            seen.add(e["event_name"])

            ws.cell(row=row, column=1, value=e["event_name"]).font = Font(name="Arial", bold=True, size=11, color="1B3A5C")
            ws.cell(row=row, column=2, value=e.get("trigger_description", "")).font = Font(name="Arial", size=10, color="616161")
            row += 1

            # Build example dataLayer push
            dl_obj = {"event": e["event_name"]}
            if "items" in e.get("parameters", {}):
                dl_obj["ecommerce"] = {}
                for k, v in e["parameters"].items():
                    if k == "items":
                        dl_obj["ecommerce"]["items"] = [{"item_id": "SKU_123", "item_name": "Example Product", "price": 38.00}]
                    else:
                        dl_obj["ecommerce"][k] = f"<{v}>"
            else:
                for k, v in e["parameters"].items():
                    dl_obj[k] = f"<{v}>"

            code = json.dumps(dl_obj, indent=2)
            code_lines = code.split("\n")
            ws.cell(row=row, column=1, value="dataLayer.push():").font = Font(name="Arial", size=9, bold=True, color="4A90C4")
            row += 1
            for line in code_lines:
                ws.cell(row=row, column=1, value=line).font = Font(name="Consolas", size=9, color="333333")
                row += 1
            row += 1  # blank row between events

    ws.column_dimensions["A"].width = 55
    ws.column_dimensions["B"].width = 50
